# History control and some other stuff
export HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoredups
export HISTCONTROL=ignoreboth
export PATH=$HOME/.bin/:$HOME/.cw/def:$HOME/.perl5/bin:$PATH
export CDPATH=".:~:~/temp/:~/devel"
export LH_INTERACTIVE="enabled"
alias ls=ls++

# Set bash options
options=( "cdable_vars" "checkwinsize" "histappend" "cdspell" )

# Set functions to execute on load
load_functions=( "set_opts" "use_lesspipe")

# Load external files DO NOT TOUCH
[[ -f ~/.yabatool/config ]] && . ~/.yabatool/config
[[ -f ~/.yabatool/bash_aliases ]] && . ~/.yabatool/bash_aliases 
[[ -f ~/.yabatool/bashrc_functions ]] && . ~/.yabatool/bashrc_functions
[[ -f ~/.yabatool/bashrc_theme ]] && . ~/.yabatool/bashrc_theme || {
    debchroot='${debian_chroot:+($debian_chroot)}'
    userhost='\[\033[01;32m\]\u@\h\[\033[00m\]:'
    workingdir='\[\033[01;34m\]\w\[\033[00m\]\$ '
}
[[ $yabatool_use_python ]] && { # Some nice and useful stuff for python programming.
    . ~/.yabatool/bash_python
}

# Prompt DO NOT TOUCH, use .bashrc_theme to customize it
# "[][]User@Host:dir[$|#] "
PS1=${debchroot}${userhost}${workingdir}

# Call external functions, DO NOT TOUCH
for i in ${load_functions[@]}; do $i; done
